// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWjUnBBd1pE1NzPe9WYlUlEEkvK3novok',
    appId: '1:77513337794:web:6ce58e43ac6c279996045b',
    messagingSenderId: '77513337794',
    projectId: 'language-2f0f0',
    authDomain: 'language-2f0f0.firebaseapp.com',
    databaseURL: 'https://language-2f0f0.firebaseio.com',
    storageBucket: 'language-2f0f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB_XBCene8Kq8mTKgWcgyzN6i6jlC4dgI',
    appId: '1:77513337794:android:7688ed7f05e09bdd96045b',
    messagingSenderId: '77513337794',
    projectId: 'language-2f0f0',
    databaseURL: 'https://language-2f0f0.firebaseio.com',
    storageBucket: 'language-2f0f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbweynLiWpylS4c9CCTmUIFTd4g_Z4yD0',
    appId: '1:77513337794:ios:6c3c17125cfb7fce96045b',
    messagingSenderId: '77513337794',
    projectId: 'language-2f0f0',
    databaseURL: 'https://language-2f0f0.firebaseio.com',
    storageBucket: 'language-2f0f0.firebasestorage.app',
    androidClientId: '77513337794-ut92cbj7b2ctpdogfu0otg7ln0s86gkp.apps.googleusercontent.com',
    iosClientId: '77513337794-sb8cnlng1msgsra4enqat319ul183gml.apps.googleusercontent.com',
    iosBundleId: 'com.example.educationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbweynLiWpylS4c9CCTmUIFTd4g_Z4yD0',
    appId: '1:77513337794:ios:6c3c17125cfb7fce96045b',
    messagingSenderId: '77513337794',
    projectId: 'language-2f0f0',
    databaseURL: 'https://language-2f0f0.firebaseio.com',
    storageBucket: 'language-2f0f0.firebasestorage.app',
    androidClientId: '77513337794-ut92cbj7b2ctpdogfu0otg7ln0s86gkp.apps.googleusercontent.com',
    iosClientId: '77513337794-sb8cnlng1msgsra4enqat319ul183gml.apps.googleusercontent.com',
    iosBundleId: 'com.example.educationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWjUnBBd1pE1NzPe9WYlUlEEkvK3novok',
    appId: '1:77513337794:web:8d9962bcb6bdc4b396045b',
    messagingSenderId: '77513337794',
    projectId: 'language-2f0f0',
    authDomain: 'language-2f0f0.firebaseapp.com',
    databaseURL: 'https://language-2f0f0.firebaseio.com',
    storageBucket: 'language-2f0f0.firebasestorage.app',
  );
}
